site_name: Optimum Documentation Hub
repo_url: https://github.com/getoptimum/optimum-docs
repo_name: getoptimum/optimum-docs
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: black
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: black
  features:
    - navigation.footer
    - navigation.sections
  plugins:
    - optimize
markdown_extensions:
  - attr_list
copyright: Copyright &copy; 2024 Optimum Engineering Team.
extra:
  generator: false
